services:
  web:
    container_name: santaku_dialogue
    tty: true
    build: .
    image: santaku_dialogue_img
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
     - db

  db:
    container_name: santaku_mysql
    image: mysql:8.4
    hostname: santaku_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: santaku_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: 'Asia/Tokyo'
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  