# Generated by Django 5.1.6 on 2025-02-21 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santaku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='表示用の名前', max_length=20)),
                ('meta_name', models.CharField(default='function name only', max_length=20)),
                ('rate', models.IntegerField(default=1)),
                ('note', models.TextField(default='ここに説明を追加')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('clear_conciliation_point', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBotFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk_text', models.CharField(max_length=20)),
                ('customer_bot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santaku.customerbot')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBotFlowSantaku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conciliation_add_point', models.IntegerField()),
                ('customer_bot_flow_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santaku.customerbotflow')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantBotBrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_cmd', models.CharField(max_length=20)),
                ('priority', models.IntegerField()),
                ('merchant_bot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santaku.customerbot')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
