# Generated by Django 5.1.6 on 2025-02-27 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santaku', '0002_conduct_customerbot_merchantbot_customerbotflow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbotflowsantaku',
            name='customer_bot_flow_id',
        ),
        migrations.RemoveField(
            model_name='customerbotflow',
            name='talk_text',
        ),
        migrations.AddField(
            model_name='customerbotflow',
            name='front_customer_utt',
            field=models.CharField(default='客役の冒頭発話', max_length=20),
        ),
        migrations.AddField(
            model_name='customerbotflow',
            name='hint_purpose',
            field=models.CharField(default='repair', max_length=20),
        ),
        migrations.AddField(
            model_name='customerbotflow',
            name='hint_relation',
            field=models.CharField(default='myself', max_length=20),
        ),
        migrations.AddField(
            model_name='customerbotflow',
            name='hint_support',
            field=models.CharField(default='empathy', max_length=20),
        ),
        migrations.AddField(
            model_name='customerbotflow',
            name='my_flow_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerbotflow',
            name='s1_back_customer_utt',
            field=models.CharField(default='客役の事後発話1', max_length=20),
        ),
        migrations.AddField(
            model_name='customerbotflow',
            name='s1_branch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerbotflow',
            name='s2_back_customer_utt',
            field=models.CharField(default='客役の事後発話2', max_length=20),
        ),
        migrations.AddField(
            model_name='customerbotflow',
            name='s2_branch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerbotflow',
            name='s3_back_customer_utt',
            field=models.CharField(default='客役の事後発話3', max_length=20),
        ),
        migrations.AddField(
            model_name='customerbotflow',
            name='s3_branch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='merchantbotbrain',
            name='merchant_bot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santaku.merchantbot'),
        ),
        migrations.AlterField(
            model_name='merchantbotbrain',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='customerbotflow',
            constraint=models.UniqueConstraint(fields=('customer_bot_id', 'my_flow_id'), name='flow_unique'),
        ),
        migrations.DeleteModel(
            name='CustomerBotFlowSantaku',
        ),
    ]
