# Generated by Django 5.1.6 on 2025-02-27 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santaku', '0003_remove_customerbotflowsantaku_customer_bot_flow_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbotflow',
            name='front_customer_utt',
            field=models.TextField(default='客役の冒頭発話', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerbotflow',
            name='hint_purpose',
            field=models.CharField(choices=[('REP', 'repair'), ('GRO', 'grows'), ('REV', 'revenge')], default='repair', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerbotflow',
            name='hint_relation',
            field=models.CharField(choices=[('MYS', 'myself'), ('IMP', 'important'), ('OTH', 'other')], default='myself', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerbotflow',
            name='hint_support',
            field=models.CharField(choices=[('EMP', 'empathy'), ('ADV', 'advice'), ('BOO', 'boost')], default='empathy', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerbotflow',
            name='s1_back_customer_utt',
            field=models.TextField(default='客役の事後発話1', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerbotflow',
            name='s1_branch',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='customerbotflow',
            name='s2_back_customer_utt',
            field=models.TextField(default='客役の事後発話2', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerbotflow',
            name='s2_branch',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='customerbotflow',
            name='s3_back_customer_utt',
            field=models.TextField(default='客役の事後発話3', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerbotflow',
            name='s3_branch',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
