# Generated by Django 5.1.6 on 2025-03-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santaku', '0004_alter_customerbotflow_front_customer_utt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbotflow',
            name='hint_purpose',
        ),
        migrations.RemoveField(
            model_name='customerbotflow',
            name='hint_relation',
        ),
        migrations.RemoveField(
            model_name='customerbotflow',
            name='hint_support',
        ),
        migrations.AddField(
            model_name='customerbotflow',
            name='s1_point',
            field=models.IntegerField(choices=[(-1, -1), (0, 0), (1, 1)], default=0),
        ),
        migrations.AddField(
            model_name='customerbotflow',
            name='s2_point',
            field=models.IntegerField(choices=[(-1, -1), (0, 0), (1, 1)], default=0),
        ),
        migrations.AddField(
            model_name='customerbotflow',
            name='s3_point',
            field=models.IntegerField(choices=[(-1, -1), (0, 0), (1, 1)], default=0),
        ),
        migrations.AlterField(
            model_name='customerbotflow',
            name='s1_back_customer_utt',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerbotflow',
            name='s2_back_customer_utt',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerbotflow',
            name='s3_back_customer_utt',
            field=models.TextField(default='', max_length=20),
        ),
    ]
