# Generated by Django 5.1.6 on 2025-03-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santaku', '0005_remove_customerbotflow_hint_purpose_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerbotflow',
            old_name='s1_branch',
            new_name='nega_branch',
        ),
        migrations.RenameField(
            model_name='customerbotflow',
            old_name='s1_point',
            new_name='nega_point',
        ),
        migrations.RenameField(
            model_name='customerbotflow',
            old_name='s2_branch',
            new_name='neut_branch',
        ),
        migrations.RenameField(
            model_name='customerbotflow',
            old_name='s2_point',
            new_name='neut_point',
        ),
        migrations.RenameField(
            model_name='customerbotflow',
            old_name='s3_branch',
            new_name='posi_branch',
        ),
        migrations.RenameField(
            model_name='customerbotflow',
            old_name='s3_point',
            new_name='posi_point',
        ),
        migrations.AlterField(
            model_name='customerbotflow',
            name='front_customer_utt',
            field=models.TextField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerbotflow',
            name='s1_back_customer_utt',
            field=models.TextField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerbotflow',
            name='s2_back_customer_utt',
            field=models.TextField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerbotflow',
            name='s3_back_customer_utt',
            field=models.TextField(blank=True, default='', max_length=20),
        ),
    ]
