# Generated by Django 5.1.6 on 2025-03-20 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santaku', '0006_rename_s1_branch_customerbotflow_nega_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbotflow',
            name='nega_branch',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='customerbotflow',
            name='neut_branch',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='customerbotflow',
            name='posi_branch',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
