# Generated by Django 5.1.6 on 2025-03-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('santaku', '0007_alter_customerbotflow_nega_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerbotflow',
            old_name='customer_bot_id',
            new_name='customer_bot',
        ),
    ]
